# Generated by Django 4.1.7 on 2023-04-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Topics',
        ),
        migrations.RenameField(
            model_name='accessrecord',
            old_name='author',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='accessrecord',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='accessrecord',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='topics',
            old_name='tname',
            new_name='TName',
        ),
        migrations.RenameField(
            model_name='webpages',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='webpages',
            old_name='tname',
            new_name='TName',
        ),
        migrations.RenameField(
            model_name='webpages',
            old_name='url',
            new_name='Url',
        ),
    ]
